fee_allocator/helpers.py

Mainnet is required too now to be passed as a header

fix: fixing pricing API subgraph queries

---

fee_allocator/accounting/recon.py
fee_allocator/tx_builder/tx_builder.py
main.py

Ci improvements

---

main.py

Don't generate payload if this is not epoch end run with a custom output file.

chore: Fix current data runs

---

main.py

- The old implementation didn't properly handle fetching of Thursday of the odd week.
- Adjustments had to be made to the logic that the last occurance of the last Thursday is properly fetched and checked against the first occurance of an odd week Thursday
- Also edge case where we are currently at a Thursday is now properly handled

FIX: Upgrade get_last_thursday_odd_week

---

fee_allocator/accounting/distribution.py
fee_allocator/accounting/settings.py

- Set total_incentives to 0 on source pool
- Set - reroute incentives on source pool
**Also changed to use a non-main branch for reroute config, change before merging**

bug: Fix Rerouting

---

fee_allocator/accounting/recon.py

Check for negative values in recon and break out the for loop to be a bit easier to read.
Use abs() to handle converting delta to postive if negative

chore: Improve Recon

---

fee_allocator/fees_collected/fees_2024-02-15_2024-02-29.json

- fee run for period 2024_02_15 to 2024_02_29
- Sheet: https://docs.google.com/spreadsheets/d/1s3wUjRneswVTicjwZG-gQ63vWGWj036_rxOKbXnVpME/edit#gid=0

Add total fees collected for fee run 2024_02_15 to 2024_02_29

---

fee_allocator/accounting/distribution.py
fee_allocator/accounting/fee_pipeline.py

reroute earned fees as well as incentives in order to make aura redistribution work properly

---

fee_allocator/accounting/collectors.py
fee_allocator/accounting/distribution.py
fee_allocator/accounting/fee_pipeline.py
requirements.txt

Waiting release of bal_addresses 0.9.1 and update from the temp version tag used here in the requirements before this should be merged.
https://github.com/BalancerMaxis/bal_addresses/pull/233
Example Run: https://github.com/BalancerMaxis/protocol_fee_allocator/actions/runs/8332269118
Example Ouput: #148

feat: Add last join exit to outputs csv so you can understand why earned fees may be 0

---

fee_allocator/fees_collected/fees_2024-03-14_2024-03-28.json

https://docs.google.com/spreadsheets/d/1as5-muEfDHFCT3GJoALKscZwXax1tc4h4KAUr1X8nvs/edit#gid=0

push 2024-W13 fees json from mimic data

---

fee_allocator/tx_builder/tx_builder.py

feat: indent transaction json

---

fee_allocator/fees_collected/fees_2024-03-28_2024-04-11.json

https://docs.google.com/spreadsheets/d/1XLz66T947yhnYKPNQflu5bV9_wCJbtBFTg28OK9sxSc/edit#gid=0

Fee data from Mimic 2024-04-11

---

fee_allocator/accounting/fee_pipeline.py
fee_allocator/fees_collected/fees_2024-04-11_2024-04-25.json

https://docs.google.com/spreadsheets/d/1vuHoHIjNY4i7cwY8zpN3jZAqQi1qMt3QD5S-IdDfhpc/edit#gid=0

Fees  2024 04 25

---

fee_allocator/fees_collected/fees_2024-04-25_2024-05-09.json

https://docs.google.com/spreadsheets/d/1jNuxzEy7xA6JwY_qLawZtFgAhws39rJxTkluYbdrhj0/edit#gid=0

Push fees from mimic 2024-05-09

---

fee_allocator/tx_builder/tx_builder.py

Clean up some of the tx-builder code and fix a rounding error that resulted in 1 wei too much being paid out.

Fix rouding error

---

.github/workflows/collect_fees.yaml
.github/workflows/collect_fees_cron.yaml
.github/workflows/collect_fees_custom.yaml
fee_allocator/accounting/collectors.py
fee_allocator/accounting/distribution.py
fee_allocator/accounting/fee_pipeline.py
main.py
requirements.txt

Do 2 passes of Aura redistribution.  The first with a buffer to allow poosl close to the line to pass over it.  Then a second with no buffer to ensure the desired end state is reached with the widest possible inclusion rate. 
Also improve dependancies

test: Aura min improve l2 handling

---

fee_allocator/fees_collected/fees_2024-05-09_2024-05-23.json

https://docs.google.com/spreadsheets/d/1DwSk-Iyk-B_DJafflcTqRHlakrA6SZnwnhsjmcHjjY0/edit#gid=0

fees from mimic 23-05-2024

---

fee_allocator/fees_collected/fees_2024-05-23_2024-06-06.json

https://docs.google.com/spreadsheets/d/1ceZIoOI4s-2EC1KLtWe6xjZpoVDKCdzrMl0bEck2diQ/edit#gid=0

Add fee data from mimic

---

fee_allocator/fees_collected/fees_2024-05-23_2024-06-06.json

Always do this when I make changes with comments/in github direct and not using IDE :(

add missing comma

---

fee_allocator/fees_collected/fees_2024-06-06_2024_06-20.json

- relevant sheet: https://docs.google.com/spreadsheets/d/1R256rLFcEWqJFW-4G5_t_WU_NPDnOKwMU85MvG5FM70/edit#gid=1505100667
- rounded down by 1 cent on all networks

feat: fee run for 2024-06-06_2024_06_20

---

fee_allocator/accounting/settings.py
fee_allocator/config_file.py
fee_allocator/helpers.py
requirements.txt

- Use studio endpoints which are rate-limited but work
- all old endpoints are shut down and need to be removed
- Cross-referenced endpoints from [balancer-sdk](https://github.com/balancer/balancer-sdk/blob/f94c6e9e3021393f0ff69e0320acd25fb6e130d3/balancer-js/src/lib/constants/config.ts)

Refactor Subgraph Endpoints

---

fee_allocator/accounting/distribution.py
fee_allocator/accounting/settings.py
fee_allocator/fees_collected/fees_2024-07-04_2024-07-18.json

blocked by: https://github.com/BalancerMaxis/multisig-ops/pull/1166

override incentive split logic

---

fee_allocator/fees_collected/fees_2024-07-04_2024-07-18.json

Not rounding this time around.  I don't think we need it anymore:
- Summary with the processed data sheet: https://docs.google.com/spreadsheets/d/1gpuy7kCg4t8ZmBkdrKPve9TocyjEcq0lPR3aMdYAW3A/edit?usp=sharing
- JSON: https://drive.google.com/file/d/1eIRVnc_sB8OTuAAfmdG3yYaLNTiNT84J/view?usp=sharing

2024-07-18 Fees  Data

---

requirements.txt

as per https://github.com/ethereum/eth-typing/issues/63 thanks to @jalbrekt85

fix: pin eth typing to <5

---

fee_allocator/helpers.py
requirements.txt

Solves #231 
1:Remove unused duplicate code.
2: Change to new query
3: Restructure query output transformation to handle new results. 
4: Remove some fixed prices that were somehow in there.

Handle the deprecated price history call.

---

.github/workflows/collect_fees_v2.yaml
.gitmodules

add v2 as submodule

---

.github/workflows/collect_fees_cron.yaml
.github/workflows/collect_fees_custom.yaml
.github/workflows/collect_fees_v2.yaml

ci: reduce core pools cron interval

---

.github/workflows/get_mimic_report.yaml

- Make generation executable via github actions
- This is a draft and should be replaced by a cron job and full integration in the future

feat: add mimic gen_report gh action

---

fee_allocator/helpers.py

github action keeps failing sometimes, trying to make it more resilient and help data team log issues
eg https://github.com/BalancerMaxis/protocol_fee_allocator/actions/runs/12767744776/attempts/1

chore: add additional gql headers for data team

---

.github/workflows/collect_fees_v2.yaml
.github/workflows/trigger_fee_collection.yaml

solves #330 
depends on https://github.com/BalancerMaxis/protocol_fee_allocator_v2/pull/38 to be merged in order to work so that v2 is aware of merged v1 mimic data

auto trigger collect fees when mimic fees are merged

---

.github/workflows/collect_fees_v2.yaml

@jalbrekt85 where would this go in the v2 repo?

docs: add paladin earnings to checklist
